# questions.py

class Question:
    def __init__(self, question, options, correct_answer):
        self.question = question
        self.options = options
        self.correct_answer = correct_answer


# Questions database
questions_data = {
    'Animal': [
        Question("What is the largest mammal in the world?",
                 ["Elephant", "Blue Whale", "Giraffe", "Great White Shark"],
                 "Blue Whale"),
        Question("Which animal is known as the 'King of the Jungle'?",
                 ["Tiger", "Lion", "Elephant", "Leopard"],
                 "Lion"),
        Question("How many hearts does an octopus have?",
                 ["1", "2", "3", "4"],
                 "3"),
        Question("What is a group of lions called?",
                 ["Pack", "Herd", "Pride", "Flock"],
                 "Pride"),
        Question("Which bird can fly backwards?",
                 ["Eagle", "Hummingbird", "Sparrow", "Penguin"],
                 "Hummingbird"),
        Question("What is the fastest land animal?",
                 ["Lion", "Cheetah", "Leopard", "Horse"],
                 "Cheetah"),
        Question("Which animal sleeps standing up?",
                 ["Dog", "Cat", "Horse", "Rabbit"],
                 "Horse"),
        Question("What is a baby kangaroo called?",
                 ["Cub", "Joey", "Calf", "Pup"],
                 "Joey"),
        Question("Which animal has the longest lifespan?",
                 ["Elephant", "Blue Whale", "Galapagos Tortoise", "Human"],
                 "Galapagos Tortoise"),
        Question("What color is a polar bear's skin?",
                 ["White", "Black", "Pink", "Brown"],
                 "Black"),
    ],

    'Math': [
        Question("What is 7 × 8?",
                 ["48", "56", "64", "72"],
                 "56"),
        Question("What is the square root of 144?",
                 ["10", "11", "12", "13"],
                 "12"),
        Question("What is 15% of 200?",
                 ["15", "20", "25", "30"],
                 "30"),
        Question("What is 9 + 10?",
                 ["18", "19", "20", "21"],
                 "19"),
        Question("What is 81 divided by 9?",
                 ["7", "8", "9", "10"],
                 "9"),
        Question("What is 5³ (5 to the power of 3)?",
                 ["15", "25", "125", "225"],
                 "125"),
        Question("What is the perimeter of a square with side 6 cm?",
                 ["12 cm", "24 cm", "36 cm", "48 cm"],
                 "24 cm"),
        Question("What is 100 - 37?",
                 ["63", "73", "67", "53"],
                 "63"),
        Question("What is 4 × 9?",
                 ["32", "36", "40", "45"],
                 "36"),
        Question("What is the value of π (pi) approximately?",
                 ["2.14", "3.14", "4.14", "5.14"],
                 "3.14"),
    ],

    'History': [
        Question("In which year did World War II end?",
                 ["1943", "1944", "1945", "1946"],
                 "1945"),
        Question("Who was the first President of the United States?",
                 ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"],
                 "George Washington"),
        Question("In which year did the Titanic sink?",
                 ["1910", "1911", "1912", "1913"],
                 "1912"),
        Question("Who discovered America in 1492?",
                 ["Marco Polo", "Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan"],
                 "Christopher Columbus"),
        Question("Which ancient civilization built the pyramids?",
                 ["Romans", "Greeks", "Egyptians", "Mayans"],
                 "Egyptians"),
        Question("Who was the first man to walk on the moon?",
                 ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Michael Collins"],
                 "Neil Armstrong"),
        Question("In which year did the Berlin Wall fall?",
                 ["1987", "1988", "1989", "1990"],
                 "1989"),
        Question("Who painted the Mona Lisa?",
                 ["Van Gogh", "Picasso", "Leonardo da Vinci", "Michelangelo"],
                 "Leonardo da Vinci"),
        Question("Which empire was ruled by Julius Caesar?",
                 ["Greek Empire", "Persian Empire", "Roman Empire", "Ottoman Empire"],
                 "Roman Empire"),
        Question("When did the French Revolution begin?",
                 ["1776", "1789", "1799", "1804"],
                 "1789"),
    ],

    'Science': [
        Question("What is the chemical symbol for water?",
                 ["O2", "H2O", "CO2", "NaCl"],
                 "H2O"),
        Question("What planet is known as the Red Planet?",
                 ["Venus", "Mars", "Jupiter", "Saturn"],
                 "Mars"),
        Question("What is the hardest natural substance on Earth?",
                 ["Gold", "Iron", "Diamond", "Platinum"],
                 "Diamond"),
        Question("What is the boiling point of water in Celsius?",
                 ["90°C", "100°C", "110°C", "120°C"],
                 "100°C"),
        Question("What is the largest organ in the human body?",
                 ["Heart", "Liver", "Skin", "Brain"],
                 "Skin"),
        Question("What gas do plants absorb from the atmosphere?",
                 ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
                 "Carbon Dioxide"),
        Question("What is the closest star to Earth?",
                 ["Sirius", "Alpha Centauri", "The Sun", "Proxima Centauri"],
                 "The Sun"),
        Question("How many bones are in the adult human body?",
                 ["206", "208", "210", "212"],
                 "206"),
        Question("What is the chemical symbol for gold?",
                 ["Go", "Gd", "Au", "Ag"],
                 "Au"),
        Question("What is the speed of light in vacuum (approximately)?",
                 ["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"],
                 "300,000 km/s"),
    ],

    'Country': [
        Question("What is the capital of France?",
                 ["London", "Berlin", "Paris", "Madrid"],
                 "Paris"),
        Question("Which country has the largest population?",
                 ["USA", "India", "China", "Russia"],
                 "China"),
        Question("What is the smallest country in the world?",
                 ["Monaco", "Vatican City", "San Marino", "Malta"],
                 "Vatican City"),
        Question("Which country is known as the Land of the Rising Sun?",
                 ["China", "Thailand", "Japan", "South Korea"],
                 "Japan"),
        Question("What is the capital of Australia?",
                 ["Sydney", "Melbourne", "Canberra", "Perth"],
                 "Canberra"),
        Question("Which country is both a country and a continent?",
                 ["Australia", "Greenland", "New Zealand", "Iceland"],
                 "Australia"),
        Question("What is the longest river in the world?",
                 ["Amazon", "Nile", "Yangtze", "Mississippi"],
                 "Nile"),
        Question("Which country has the most natural lakes?",
                 ["USA", "Russia", "Canada", "Brazil"],
                 "Canada"),
        Question("What is the capital of Brazil?",
                 ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
                 "Brasília"),
        Question("Which country is famous for the Great Wall?",
                 ["Japan", "India", "China", "Korea"],
                 "China"),
    ]
}